// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: audio.proto

package serviciosAudio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{0}
}

type AudioTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        int32                  `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioTypeRequest) Reset() {
	*x = AudioTypeRequest{}
	mi := &file_audio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioTypeRequest) ProtoMessage() {}

func (x *AudioTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioTypeRequest.ProtoReflect.Descriptor instead.
func (*AudioTypeRequest) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{1}
}

func (x *AudioTypeRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

type AudioByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       int32                  `protobuf:"varint,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioByIdRequest) Reset() {
	*x = AudioByIdRequest{}
	mi := &file_audio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioByIdRequest) ProtoMessage() {}

func (x *AudioByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioByIdRequest.ProtoReflect.Descriptor instead.
func (*AudioByIdRequest) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{2}
}

func (x *AudioByIdRequest) GetAudioId() int32 {
	if x != nil {
		return x.AudioId
	}
	return 0
}

type AudioType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioType) Reset() {
	*x = AudioType{}
	mi := &file_audio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioType) ProtoMessage() {}

func (x *AudioType) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioType.ProtoReflect.Descriptor instead.
func (*AudioType) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{3}
}

func (x *AudioType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AudioType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AudioTypeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AudioType           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioTypeList) Reset() {
	*x = AudioTypeList{}
	mi := &file_audio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioTypeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioTypeList) ProtoMessage() {}

func (x *AudioTypeList) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioTypeList.ProtoReflect.Descriptor instead.
func (*AudioTypeList) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{4}
}

func (x *AudioTypeList) GetItems() []*AudioType {
	if x != nil {
		return x.Items
	}
	return nil
}

type AudioSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId        int32                  `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioSummary) Reset() {
	*x = AudioSummary{}
	mi := &file_audio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioSummary) ProtoMessage() {}

func (x *AudioSummary) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioSummary.ProtoReflect.Descriptor instead.
func (*AudioSummary) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{5}
}

func (x *AudioSummary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AudioSummary) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *AudioSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type AudioList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AudioSummary        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioList) Reset() {
	*x = AudioList{}
	mi := &file_audio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioList) ProtoMessage() {}

func (x *AudioList) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioList.ProtoReflect.Descriptor instead.
func (*AudioList) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{6}
}

func (x *AudioList) GetItems() []*AudioSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

type MetadataItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataItem) Reset() {
	*x = MetadataItem{}
	mi := &file_audio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataItem) ProtoMessage() {}

func (x *MetadataItem) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataItem.ProtoReflect.Descriptor instead.
func (*MetadataItem) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{7}
}

func (x *MetadataItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AudioDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId        int32                  `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	TypeName      string                 `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	Metadata      []*MetadataItem        `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioDetails) Reset() {
	*x = AudioDetails{}
	mi := &file_audio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDetails) ProtoMessage() {}

func (x *AudioDetails) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDetails.ProtoReflect.Descriptor instead.
func (*AudioDetails) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{8}
}

func (x *AudioDetails) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AudioDetails) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *AudioDetails) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *AudioDetails) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AudioDetails) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AudioDetails) GetMetadata() []*MetadataItem {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_audio_proto protoreflect.FileDescriptor

const file_audio_proto_rawDesc = "" +
	"\n" +
	"\vaudio.proto\x12\tservicios\"\a\n" +
	"\x05Empty\"+\n" +
	"\x10AudioTypeRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\x05R\x06typeId\"-\n" +
	"\x10AudioByIdRequest\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\x05R\aaudioId\"/\n" +
	"\tAudioType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\";\n" +
	"\rAudioTypeList\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.servicios.AudioTypeR\x05items\"M\n" +
	"\fAudioSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\x05R\x06typeId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\":\n" +
	"\tAudioList\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.servicios.AudioSummaryR\x05items\"6\n" +
	"\fMetadataItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xbb\x01\n" +
	"\fAudioDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\x05R\x06typeId\x12\x1b\n" +
	"\ttype_name\x18\x03 \x01(\tR\btypeName\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x123\n" +
	"\bmetadata\x18\x06 \x03(\v2\x17.servicios.MetadataItemR\bmetadata2\xdf\x01\n" +
	"\x0fMetadataService\x12<\n" +
	"\x0eListAudioTypes\x12\x10.servicios.Empty\x1a\x18.servicios.AudioTypeList\x12E\n" +
	"\x10ListAudiosByType\x12\x1b.servicios.AudioTypeRequest\x1a\x14.servicios.AudioList\x12G\n" +
	"\x0fGetAudioDetails\x12\x1b.servicios.AudioByIdRequest\x1a\x17.servicios.AudioDetailsB\x11Z\x0f/serviciosAudiob\x06proto3"

var (
	file_audio_proto_rawDescOnce sync.Once
	file_audio_proto_rawDescData []byte
)

func file_audio_proto_rawDescGZIP() []byte {
	file_audio_proto_rawDescOnce.Do(func() {
		file_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_proto_rawDesc), len(file_audio_proto_rawDesc)))
	})
	return file_audio_proto_rawDescData
}

var file_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_audio_proto_goTypes = []any{
	(*Empty)(nil),            // 0: servicios.Empty
	(*AudioTypeRequest)(nil), // 1: servicios.AudioTypeRequest
	(*AudioByIdRequest)(nil), // 2: servicios.AudioByIdRequest
	(*AudioType)(nil),        // 3: servicios.AudioType
	(*AudioTypeList)(nil),    // 4: servicios.AudioTypeList
	(*AudioSummary)(nil),     // 5: servicios.AudioSummary
	(*AudioList)(nil),        // 6: servicios.AudioList
	(*MetadataItem)(nil),     // 7: servicios.MetadataItem
	(*AudioDetails)(nil),     // 8: servicios.AudioDetails
}
var file_audio_proto_depIdxs = []int32{
	3, // 0: servicios.AudioTypeList.items:type_name -> servicios.AudioType
	5, // 1: servicios.AudioList.items:type_name -> servicios.AudioSummary
	7, // 2: servicios.AudioDetails.metadata:type_name -> servicios.MetadataItem
	0, // 3: servicios.MetadataService.ListAudioTypes:input_type -> servicios.Empty
	1, // 4: servicios.MetadataService.ListAudiosByType:input_type -> servicios.AudioTypeRequest
	2, // 5: servicios.MetadataService.GetAudioDetails:input_type -> servicios.AudioByIdRequest
	4, // 6: servicios.MetadataService.ListAudioTypes:output_type -> servicios.AudioTypeList
	6, // 7: servicios.MetadataService.ListAudiosByType:output_type -> servicios.AudioList
	8, // 8: servicios.MetadataService.GetAudioDetails:output_type -> servicios.AudioDetails
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_audio_proto_init() }
func file_audio_proto_init() {
	if File_audio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_proto_rawDesc), len(file_audio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audio_proto_goTypes,
		DependencyIndexes: file_audio_proto_depIdxs,
		MessageInfos:      file_audio_proto_msgTypes,
	}.Build()
	File_audio_proto = out.File
	file_audio_proto_goTypes = nil
	file_audio_proto_depIdxs = nil
}
