// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: audio.proto

package serviciosAudio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataService_ListAudioTypes_FullMethodName   = "/servicios.MetadataService/ListAudioTypes"
	MetadataService_ListAudiosByType_FullMethodName = "/servicios.MetadataService/ListAudiosByType"
	MetadataService_GetAudioDetails_FullMethodName  = "/servicios.MetadataService/GetAudioDetails"
)

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetadataServiceClient interface {
	ListAudioTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AudioTypeList, error)
	ListAudiosByType(ctx context.Context, in *AudioTypeRequest, opts ...grpc.CallOption) (*AudioList, error)
	GetAudioDetails(ctx context.Context, in *AudioByIdRequest, opts ...grpc.CallOption) (*AudioDetails, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) ListAudioTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AudioTypeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioTypeList)
	err := c.cc.Invoke(ctx, MetadataService_ListAudioTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ListAudiosByType(ctx context.Context, in *AudioTypeRequest, opts ...grpc.CallOption) (*AudioList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioList)
	err := c.cc.Invoke(ctx, MetadataService_ListAudiosByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetAudioDetails(ctx context.Context, in *AudioByIdRequest, opts ...grpc.CallOption) (*AudioDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioDetails)
	err := c.cc.Invoke(ctx, MetadataService_GetAudioDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility.
type MetadataServiceServer interface {
	ListAudioTypes(context.Context, *Empty) (*AudioTypeList, error)
	ListAudiosByType(context.Context, *AudioTypeRequest) (*AudioList, error)
	GetAudioDetails(context.Context, *AudioByIdRequest) (*AudioDetails, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataServiceServer struct{}

func (UnimplementedMetadataServiceServer) ListAudioTypes(context.Context, *Empty) (*AudioTypeList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAudioTypes not implemented")
}
func (UnimplementedMetadataServiceServer) ListAudiosByType(context.Context, *AudioTypeRequest) (*AudioList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAudiosByType not implemented")
}
func (UnimplementedMetadataServiceServer) GetAudioDetails(context.Context, *AudioByIdRequest) (*AudioDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAudioDetails not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}
func (UnimplementedMetadataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	// If the following call panics, it indicates UnimplementedMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_ListAudioTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListAudioTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ListAudioTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListAudioTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ListAudiosByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListAudiosByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ListAudiosByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListAudiosByType(ctx, req.(*AudioTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetAudioDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetAudioDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetAudioDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetAudioDetails(ctx, req.(*AudioByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicios.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAudioTypes",
			Handler:    _MetadataService_ListAudioTypes_Handler,
		},
		{
			MethodName: "ListAudiosByType",
			Handler:    _MetadataService_ListAudiosByType_Handler,
		},
		{
			MethodName: "GetAudioDetails",
			Handler:    _MetadataService_GetAudioDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audio.proto",
}
